# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jesusOmar
email: jesus.fndz@gmail.com
subtitle: Random thoughts of a code junkie.
description: > # this means to ignore newlines until "baseurl:"
  Randome thoughts of a code junkie. Mainly php with Laravel and/or Symfony ramblings and me hating on Doctrine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jesusomar.com" # the base hostname & protocol for your site
twitter_username: jesusOmar
github_username:  jesusOmar

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-gist
